### ISSUE TITLE
flagged

### ISSUE THREAD

**Issue by SlotthCode** [Pr0t0ns/HSL-Reverse#2]
this is badly flagged. hit up my dms

**Comment by Pr0t0ns** [comment]
I want to quickly reply to this and say it’s impossible to generate a flagged HSL it’s all about the checkconfig request to get the JWT itself that is what could be flagged which then would make a flagged HSL value lol their is nothing wrong with how I generate/format the HSL.

**Comment by dropout1337** [comment]
Proton, you do realise that when you stated `"1" # this is the value h0nde made all that unnecessary code for` this is from very old code. The "1" aka that value actually does matter.

**Comment by Pr0t0ns** [comment]
> Proton, you do realise that when you stated `"1" # this is the value h0nde made all that unnecessary code for` this is from very old code. The "1" aka that value actually does matter.

Yeah not too long after I posted this I realized I'm just stupid
